# Generated by Django 4.2.1 on 2023-06-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='onlineratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='userratings',
            field=models.CharField(default='', max_length=5),
        ),
    ]
