# Generated by Django 4.2.1 on 2023-06-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_onlineratings_product_userratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='onlineratings',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='userratings',
            field=models.CharField(default='', max_length=10),
        ),
    ]
