# Generated by Django 3.0.14 on 2023-07-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20230703_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='post',
            new_name='product',
        ),
    ]
