# Generated by Django 3.0.14 on 2023-07-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20230703_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='product',
            new_name='post',
        ),
    ]
